export const BOTSWANA = {
  count: 20,
  artists: [
    { name: "Meleko Mokgosi", medium: "Painting", city: "Gaborone", gender: "male", birth_year: 1981, wikipedia: "Meleko Mokgosi" },
    { name: "Ann Gollifer", medium: "Painting", city: "Gaborone", gender: "female", birth_year: 1968 },
    { name: "Thabiso Mohare", medium: "Photography", city: "Gaborone", gender: "male", birth_year: 1990 },
    { name: "Wilson Ngoni", medium: "Sculpture", city: "Francistown", gender: "male", birth_year: 1975 },
    { name: "Sedireng Olehile", medium: "Painting", city: "Gaborone", gender: "female", birth_year: 1988 },
    { name: "Ntebogang Gaboabi", medium: "Textile", city: "Gaborone", gender: "female", birth_year: 1991 },
    { name: "Kabelo Kim", medium: "Painting", city: "Gaborone", gender: "male", birth_year: 1993 },
    { name: "Motho Kobori", medium: "Mixed media", city: "Maun", gender: "male", birth_year: 1987 },
    { name: "Lobelo Lobelo", medium: "Sculpture", city: "Gaborone", gender: "male", birth_year: 1970 },
    { name: "Boniface Chiwawa", medium: "Painting", city: "Gaborone", gender: "male", birth_year: 1982 },
    { name: "Ompile Kgeletsane", medium: "Photography", city: "Gaborone", gender: "female", birth_year: 1994 },
    { name: "Thato Romel", medium: "Digital art", city: "Gaborone", gender: "male", birth_year: 1995 },
    { name: "Moffat Makuto", medium: "Painting", city: "Gaborone", gender: "male", birth_year: 1965 },
    { name: "Gofiwa Matlhogonolo", medium: "Drawing", city: "Gaborone", gender: "female", birth_year: 1992 },
    { name: "Katlego Tladinyane", medium: "Sculpture", city: "Gaborone", gender: "male", birth_year: 1989 },
    { name: "Gaone Rammolai", medium: "Painting", city: "Gaborone", gender: "female", birth_year: 1990 },
    { name: "Moalosi Moalosi", medium: "Printmaking", city: "Gaborone", gender: "male", birth_year: 1978 },
    { name: "Keabetswe Ncube", medium: "Mixed media", city: "Gaborone", gender: "female", birth_year: 1991 },
    { name: "Tshepo Segole", medium: "Painting", city: "Gaborone", gender: "male", birth_year: 1986 },
    { name: "Boitumelo Khurumela", medium: "Textile", city: "Gaborone", gender: "female", birth_year: 1993 },
  ],
};
