/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as RendersRouteImport } from './routes/renders'
import { Route as NotifyRouteImport } from './routes/notify'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as CollateralRouteImport } from './routes/collateral'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PieceCodeRouteImport } from './routes/piece.$code'
import { Route as NotifyInboxRouteImport } from './routes/notify.inbox'
import { Route as CheckoutMockRouteImport } from './routes/checkout.mock'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout.callback'
import { Route as ArtistCodeRouteImport } from './routes/artist.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as VerifyCertCodeRouteImport } from './routes/verify.cert.$code'
import { Route as NotifyReelIdRouteImport } from './routes/notify.reel.$id'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as ApiCronAuctionsRouteImport } from './routes/api/cron/auctions'
import { Route as ApiBridgeEnterRouteImport } from './routes/api/bridge.enter'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const RendersRoute = RendersRouteImport.update({
  id: '/renders',
  path: '/renders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyRoute = NotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const CollateralRoute = CollateralRouteImport.update({
  id: '/collateral',
  path: '/collateral',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PieceCodeRoute = PieceCodeRouteImport.update({
  id: '/piece/$code',
  path: '/piece/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyInboxRoute = NotifyInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => NotifyRoute,
} as any)
const CheckoutMockRoute = CheckoutMockRouteImport.update({
  id: '/checkout/mock',
  path: '/checkout/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/checkout/callback',
  path: '/checkout/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistCodeRoute = ArtistCodeRouteImport.update({
  id: '/artist/$code',
  path: '/artist/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertCodeRoute = VerifyCertCodeRouteImport.update({
  id: '/verify/cert/$code',
  path: '/verify/cert/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyReelIdRoute = NotifyReelIdRouteImport.update({
  id: '/reel/$id',
  path: '/reel/$id',
  getParentRoute: () => NotifyRoute,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAuctionsRoute = ApiCronAuctionsRouteImport.update({
  id: '/api/cron/auctions',
  path: '/api/cron/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeEnterRoute = ApiBridgeEnterRouteImport.update({
  id: '/api/bridge/enter',
  path: '/api/bridge/enter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auction': typeof AuctionRoute
  '/collateral': typeof CollateralRoute
  '/disputes': typeof DisputesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/lounge': typeof LoungeRoute
  '/notify': typeof NotifyRouteWithChildren
  '/renders': typeof RendersRoute
  '/studio': typeof StudioRoute
  '/submit': typeof SubmitRoute
  '/verification': typeof VerificationRoute
  '/api/chat': typeof ApiChatRoute
  '/artist/$code': typeof ArtistCodeRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/mock': typeof CheckoutMockRoute
  '/notify/inbox': typeof NotifyInboxRoute
  '/piece/$code': typeof PieceCodeRoute
  '/api/bridge/enter': typeof ApiBridgeEnterRoute
  '/api/cron/auctions': typeof ApiCronAuctionsRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/notify/reel/$id': typeof NotifyReelIdRoute
  '/verify/cert/$code': typeof VerifyCertCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auction': typeof AuctionRoute
  '/collateral': typeof CollateralRoute
  '/disputes': typeof DisputesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/lounge': typeof LoungeRoute
  '/notify': typeof NotifyRouteWithChildren
  '/renders': typeof RendersRoute
  '/studio': typeof StudioRoute
  '/submit': typeof SubmitRoute
  '/verification': typeof VerificationRoute
  '/api/chat': typeof ApiChatRoute
  '/artist/$code': typeof ArtistCodeRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/mock': typeof CheckoutMockRoute
  '/notify/inbox': typeof NotifyInboxRoute
  '/piece/$code': typeof PieceCodeRoute
  '/api/bridge/enter': typeof ApiBridgeEnterRoute
  '/api/cron/auctions': typeof ApiCronAuctionsRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/notify/reel/$id': typeof NotifyReelIdRoute
  '/verify/cert/$code': typeof VerifyCertCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auction': typeof AuctionRoute
  '/collateral': typeof CollateralRoute
  '/disputes': typeof DisputesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/lounge': typeof LoungeRoute
  '/notify': typeof NotifyRouteWithChildren
  '/renders': typeof RendersRoute
  '/studio': typeof StudioRoute
  '/submit': typeof SubmitRoute
  '/verification': typeof VerificationRoute
  '/api/chat': typeof ApiChatRoute
  '/artist/$code': typeof ArtistCodeRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/mock': typeof CheckoutMockRoute
  '/notify/inbox': typeof NotifyInboxRoute
  '/piece/$code': typeof PieceCodeRoute
  '/api/bridge/enter': typeof ApiBridgeEnterRoute
  '/api/cron/auctions': typeof ApiCronAuctionsRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/notify/reel/$id': typeof NotifyReelIdRoute
  '/verify/cert/$code': typeof VerifyCertCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auction'
    | '/collateral'
    | '/disputes'
    | '/events'
    | '/login'
    | '/lounge'
    | '/notify'
    | '/renders'
    | '/studio'
    | '/submit'
    | '/verification'
    | '/api/chat'
    | '/artist/$code'
    | '/checkout/callback'
    | '/checkout/mock'
    | '/notify/inbox'
    | '/piece/$code'
    | '/api/bridge/enter'
    | '/api/cron/auctions'
    | '/api/webhooks/paystack'
    | '/notify/reel/$id'
    | '/verify/cert/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auction'
    | '/collateral'
    | '/disputes'
    | '/events'
    | '/login'
    | '/lounge'
    | '/notify'
    | '/renders'
    | '/studio'
    | '/submit'
    | '/verification'
    | '/api/chat'
    | '/artist/$code'
    | '/checkout/callback'
    | '/checkout/mock'
    | '/notify/inbox'
    | '/piece/$code'
    | '/api/bridge/enter'
    | '/api/cron/auctions'
    | '/api/webhooks/paystack'
    | '/notify/reel/$id'
    | '/verify/cert/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auction'
    | '/collateral'
    | '/disputes'
    | '/events'
    | '/login'
    | '/lounge'
    | '/notify'
    | '/renders'
    | '/studio'
    | '/submit'
    | '/verification'
    | '/api/chat'
    | '/artist/$code'
    | '/checkout/callback'
    | '/checkout/mock'
    | '/notify/inbox'
    | '/piece/$code'
    | '/api/bridge/enter'
    | '/api/cron/auctions'
    | '/api/webhooks/paystack'
    | '/notify/reel/$id'
    | '/verify/cert/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuctionRoute: typeof AuctionRoute
  CollateralRoute: typeof CollateralRoute
  DisputesRoute: typeof DisputesRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  LoungeRoute: typeof LoungeRoute
  NotifyRoute: typeof NotifyRouteWithChildren
  RendersRoute: typeof RendersRoute
  StudioRoute: typeof StudioRoute
  SubmitRoute: typeof SubmitRoute
  VerificationRoute: typeof VerificationRoute
  ApiChatRoute: typeof ApiChatRoute
  ArtistCodeRoute: typeof ArtistCodeRoute
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CheckoutMockRoute: typeof CheckoutMockRoute
  PieceCodeRoute: typeof PieceCodeRoute
  ApiBridgeEnterRoute: typeof ApiBridgeEnterRoute
  ApiCronAuctionsRoute: typeof ApiCronAuctionsRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
  VerifyCertCodeRoute: typeof VerifyCertCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renders': {
      id: '/renders'
      path: '/renders'
      fullPath: '/renders'
      preLoaderRoute: typeof RendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify': {
      id: '/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof NotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collateral': {
      id: '/collateral'
      path: '/collateral'
      fullPath: '/collateral'
      preLoaderRoute: typeof CollateralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piece/$code': {
      id: '/piece/$code'
      path: '/piece/$code'
      fullPath: '/piece/$code'
      preLoaderRoute: typeof PieceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify/inbox': {
      id: '/notify/inbox'
      path: '/inbox'
      fullPath: '/notify/inbox'
      preLoaderRoute: typeof NotifyInboxRouteImport
      parentRoute: typeof NotifyRoute
    }
    '/checkout/mock': {
      id: '/checkout/mock'
      path: '/checkout/mock'
      fullPath: '/checkout/mock'
      preLoaderRoute: typeof CheckoutMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/checkout/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$code': {
      id: '/artist/$code'
      path: '/artist/$code'
      fullPath: '/artist/$code'
      preLoaderRoute: typeof ArtistCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/cert/$code': {
      id: '/verify/cert/$code'
      path: '/verify/cert/$code'
      fullPath: '/verify/cert/$code'
      preLoaderRoute: typeof VerifyCertCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify/reel/$id': {
      id: '/notify/reel/$id'
      path: '/reel/$id'
      fullPath: '/notify/reel/$id'
      preLoaderRoute: typeof NotifyReelIdRouteImport
      parentRoute: typeof NotifyRoute
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/auctions': {
      id: '/api/cron/auctions'
      path: '/api/cron/auctions'
      fullPath: '/api/cron/auctions'
      preLoaderRoute: typeof ApiCronAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/enter': {
      id: '/api/bridge/enter'
      path: '/api/bridge/enter'
      fullPath: '/api/bridge/enter'
      preLoaderRoute: typeof ApiBridgeEnterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotifyRouteChildren {
  NotifyInboxRoute: typeof NotifyInboxRoute
  NotifyReelIdRoute: typeof NotifyReelIdRoute
}

const NotifyRouteChildren: NotifyRouteChildren = {
  NotifyInboxRoute: NotifyInboxRoute,
  NotifyReelIdRoute: NotifyReelIdRoute,
}

const NotifyRouteWithChildren =
  NotifyRoute._addFileChildren(NotifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuctionRoute: AuctionRoute,
  CollateralRoute: CollateralRoute,
  DisputesRoute: DisputesRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  LoungeRoute: LoungeRoute,
  NotifyRoute: NotifyRouteWithChildren,
  RendersRoute: RendersRoute,
  StudioRoute: StudioRoute,
  SubmitRoute: SubmitRoute,
  VerificationRoute: VerificationRoute,
  ApiChatRoute: ApiChatRoute,
  ArtistCodeRoute: ArtistCodeRoute,
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CheckoutMockRoute: CheckoutMockRoute,
  PieceCodeRoute: PieceCodeRoute,
  ApiBridgeEnterRoute: ApiBridgeEnterRoute,
  ApiCronAuctionsRoute: ApiCronAuctionsRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
  VerifyCertCodeRoute: VerifyCertCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
