-- Generated by scripts/gen-outreach-artists.mjs from data/nigerian-artists-outreach-100.csv.
-- Do not edit by hand — update the CSV and re-run the generator.
-- Only CSV-backed facts are seeded; unknown fields stay NULL.
--
-- Outreach artist profiles: real Nigerian artists we are reaching out to. They
-- are NOT paying members, so they carry profile_status = 'unclaimed_outreach'
-- and content_source = 'outreach' to keep them out of the curated allocation
-- lanes while still being browsable and addressable at /artist/<short_code>.

alter table public.artists
  add column if not exists profile_status text not null default 'active',
  add column if not exists primary_medium text,
  add column if not exists website text,
  add column if not exists outreach_note text,
  add column if not exists outreach_source text,
  add column if not exists outreach_status text;

comment on column public.artists.profile_status is
  'active = onboarded artist; unclaimed_outreach = curated outreach record, not a member.';
comment on column public.artists.outreach_note is
  'Verbatim curator note from the outreach CSV. Never an artist-authored bio.';

do $$ begin
  alter table public.artists add constraint artists_profile_status_chk
    check (profile_status in ('active', 'unclaimed_outreach'));
exception when duplicate_object then null; end $$;

-- 'outreach' joins the existing content_source buckets. Both historical check
-- constraints are replaced by a single up-to-date one.
alter table public.artists drop constraint if exists artists_content_source_check;
alter table public.artists drop constraint if exists artists_content_source_chk;
alter table public.artists
  add constraint artists_content_source_chk
  check (content_source in ('live', 'mock', 'artstage', 'outreach'));

create index if not exists idx_artists_profile_status on public.artists(profile_status);
create index if not exists idx_artists_primary_medium on public.artists(primary_medium);

insert into public.artists (
  short_code, name, primary_medium, domicile_city, country, website,
  outreach_note, outreach_source, outreach_status, profile_status, content_source
) values
  ('ART-OUT-001', 'Dotun Popoola', 'Sculpture', 'Ile-Ife', 'Nigeria', 'dotunpopo.com', 'Founder Scrap Art Museum; scrap-metal sculptor', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-002', 'Peju Alatise', 'Mixed media', 'Lagos', 'Nigeria', 'pejualatise.com', 'ART X Lagos regular; Yoruba mythology themes', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-003', 'Victor Ehikhamenor', 'Painting', 'Lagos', 'Nigeria', 'ehikhamenor.com', 'Writer, artist; Nsibidi and contemporary forms', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-004', 'Bruce Onobrakpeya', 'Printmaking', 'Lagos', 'Nigeria', null, 'Pioneer modern Nigerian printmaker', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-005', 'Yusuf Grillo', 'Painting', 'Lagos', 'Nigeria', null, 'Modernist painter; Yaba Tech legacy', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-006', 'Nike Okundaye', 'Textile', 'Osogbo', 'Nigeria', 'nikeart.com', 'Adire master; Nike Art Gallery', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-007', 'Ndidi Dike', 'Mixed media', 'Lagos', 'Nigeria', null, 'Sculpture and installation; Lagos Biennial', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-008', 'Rom Isichei', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary figurative painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-009', 'Peju Obasa', 'Sculpture', 'Lagos', 'Nigeria', null, 'Ceramic and mixed media sculptor', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-010', 'Adaeze Okonkwo', 'Painting', 'Lagos', 'Nigeria', 'myafriartx.netlify.app', 'Nsibidi-influenced oil abstractions', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-011', 'Marcus Odia', 'Painting', 'Benin City', 'Nigeria', null, 'Contemporary Benin painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-012', 'Samson Bakare', 'Painting', 'Lagos', 'Nigeria', null, 'Pop surrealism; ART X Lagos', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-013', 'Olatunde Alara', 'Digital art', 'Lagos', 'Nigeria', null, 'Afrofuturist digital illustrator', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-014', 'Drew Aquilma', 'Photography', 'Lagos', 'Nigeria', null, 'Fashion and portrait photographer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-015', 'Ade Adekola', 'Photography', 'Lagos', 'Nigeria', null, 'Street and documentary photography', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-016', 'Abiodun Olaku', 'Painting', 'Lagos', 'Nigeria', null, 'Lagos streetscape realist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-017', 'Ben Osaghae', 'Painting', 'Lagos', 'Nigeria', null, 'Social commentary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-018', 'Gerald Chukwuma', 'Sculpture', 'Lagos', 'Nigeria', null, 'Wood relief and metal sculpture', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-019', 'Nengi Omuku', 'Painting', 'Lagos', 'Nigeria', null, 'Figurative and landscape painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-020', 'Modupeola Fedeke', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary portraiture', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-021', 'Tyna Adebowale', 'Painting', 'Lagos', 'Nigeria', null, 'Gender and identity themes', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-022', 'Wura-Natasha Ogunji', 'Drawing', 'Lagos', 'Nigeria', null, 'Performance and drawing', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-023', 'Karimah Ashadu', 'Film/Video', 'Lagos', 'Nigeria', null, 'Documentary filmmaker and artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-024', 'Ayo Akingbola', 'Painting', 'Lagos', 'Nigeria', null, 'Abstract and figurative works', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-025', 'Ayobola Kekere-Ekun', 'Textile', 'Lagos', 'Nigeria', null, 'Paper quilling and textile art', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-026', 'Drew Gilbert', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary Lagos scenes', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-027', 'Elias Maman', 'Painting', 'Kaduna', 'Nigeria', null, 'Northern Nigerian contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-028', 'Emeka Ogboh', 'Sound art', 'Lagos', 'Nigeria', null, 'Sound and installation artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-029', 'George Osodi', 'Photography', 'Lagos', 'Nigeria', null, 'Documentary photographer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-030', 'Halima Abubakar', 'Painting', 'Kano', 'Nigeria', null, 'Northern Nigerian painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-031', 'Ibe Ananaba', 'Painting', 'Lagos', 'Nigeria', null, 'Watercolor street scenes', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-032', 'Johnson Uwadinma', 'Painting', 'Abuja', 'Nigeria', null, 'Contemporary abstraction', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-033', 'Karo Akpokiere', 'Drawing', 'Lagos', 'Nigeria', null, 'Graphic and drawing practice', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-034', 'Karo Omu', 'Mixed media', 'Lagos', 'Nigeria', null, 'Collage and mixed media', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-035', 'Kelechi Amadi-Obi', 'Photography', 'Lagos', 'Nigeria', null, 'Fashion photographer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-036', 'Kudzanai Chiurai', 'Painting', 'Lagos', 'Nigeria', null, 'Exhibited in Lagos; political themes', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-037', 'Lerato Shadi', 'Installation', 'Lagos', 'Nigeria', null, 'Performance and installation', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-038', 'Mary Sibande', 'Sculpture', 'Lagos', 'Nigeria', null, 'Exhibited in Nigeria; textile sculpture', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-039', 'Moyosore Martins', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-040', 'Niyi Olagunju', 'Sculpture', 'Lagos', 'Nigeria', null, 'Metal and mixed media sculpture', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-041', 'Olu Amoda', 'Sculpture', 'Lagos', 'Nigeria', null, 'Metal sculpture pioneer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-042', 'Olu Oguibe', 'Installation', 'Lagos', 'Nigeria', null, 'Conceptual artist and writer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-043', 'Onyeka Ibe', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary figurative painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-044', 'Paul Oluwole', 'Painting', 'Lagos', 'Nigeria', null, 'Abstract expressionist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-045', 'Ruby Onyinyechi Amanze', 'Drawing', 'Lagos', 'Nigeria', null, 'Drawing and paper works', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-046', 'Samuel Onyilo', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary Lagos painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-047', 'Tayo Adenaike', 'Painting', 'Lagos', 'Nigeria', null, 'Uli-inspired contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-048', 'Temitayo Ogunbiyi', 'Installation', 'Lagos', 'Nigeria', null, 'Installation and drawing', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-049', 'Toyin Ojih Odutola', 'Drawing', 'Lagos', 'Nigeria', null, 'Nigerian-American; exhibited in Lagos', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-050', 'Uche Uzorka', 'Painting', 'Lagos', 'Nigeria', null, 'Mixed media painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-051', 'Ugo Nwagbogu', 'Curator', 'Lagos', 'Nigeria', 'nle.org', 'NLE Lagos founder and curator', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-052', 'Yadichinma Ukoha-Kalu', 'Drawing', 'Lagos', 'Nigeria', null, 'Line drawing and animation', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-053', 'Zina Saro-Wiwa', 'Video', 'Lagos', 'Nigeria', null, 'Video and installation artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-054', 'Adejoke Tugbiyele', 'Sculpture', 'Lagos', 'Nigeria', null, 'Wire and mixed media sculpture', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-055', 'Aghogho Akpome', 'Painting', 'Warri', 'Nigeria', null, 'Delta State contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-056', 'Aina Onabolu', 'Painting', 'Lagos', 'Nigeria', null, 'Pioneer Nigerian modern painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-057', 'Akinola Lasekan', 'Painting', 'Lagos', 'Nigeria', null, 'Political cartoonist and painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-058', 'Akintunde Akinleye', 'Photography', 'Lagos', 'Nigeria', null, 'Reuters photographer; documentary', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-059', 'Amarachi Okafor', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-060', 'Chika Okeke-Agulu', 'Curator', 'Lagos', 'Nigeria', null, 'Art historian and curator', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-061', 'Chris Afuba', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary abstraction', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-062', 'Dipo Onabanjo', 'Photography', 'Lagos', 'Nigeria', null, 'Street photography', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-063', 'Eddy Kamuanga', 'Painting', 'Lagos', 'Nigeria', null, 'Exhibited in Lagos galleries', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-064', 'Emeka Okereke', 'Photography', 'Lagos', 'Nigeria', null, 'Invisible Borders founder', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-065', 'Ernest Nkwocha', 'Sculpture', 'Lagos', 'Nigeria', null, 'Wood sculptor', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-066', 'Hermann Nwali', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-067', 'Ima Mfon', 'Photography', 'Lagos', 'Nigeria', null, 'Portrait photographer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-068', 'Jelili Atiku', 'Performance', 'Lagos', 'Nigeria', null, 'Performance artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-069', 'Kainene Mama', 'Textile', 'Lagos', 'Nigeria', null, 'Textile and fashion art', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-070', 'Kelechi Nwafor', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-071', 'Kolade Oshinowo', 'Painting', 'Lagos', 'Nigeria', null, 'Watercolor and oil painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-072', 'Lakin Ogunbanwo', 'Photography', 'Lagos', 'Nigeria', null, 'Fashion portrait photographer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-073', 'Lemi Ghariokwu', 'Illustration', 'Lagos', 'Nigeria', null, 'Fela album cover artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-074', 'Moyo Okediji', 'Painting', 'Lagos', 'Nigeria', null, 'Yoruba art scholar and painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-075', 'Ndidi Emefiele', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-076', 'Obiora Anidi', 'Sculpture', 'Lagos', 'Nigeria', null, 'Metal sculptor', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-077', 'Ola-Dele Kuku', 'Architecture/Art', 'Lagos', 'Nigeria', null, 'Architect and installation', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-078', 'Oliver Enwonwu', 'Painting', 'Lagos', 'Nigeria', null, 'Ben Enwonwu Foundation director', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-079', 'Onyeka Igwe', 'Film', 'Lagos', 'Nigeria', null, 'Filmmaker and artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-080', 'Otobong Nkanga', 'Installation', 'Lagos', 'Nigeria', null, 'Exhibited extensively in Lagos', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-081', 'Paul Onditi', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-082', 'Philip Ojo', 'Painting', 'Lagos', 'Nigeria', null, 'Contemporary painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-083', 'Raquel van Haver', 'Painting', 'Lagos', 'Nigeria', null, 'Exhibited at ART X Lagos', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-084', 'Senzeni Marasela', 'Textile', 'Lagos', 'Nigeria', null, 'Exhibited in Lagos', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-085', 'Uche James-Iroha', 'Photography', 'Lagos', 'Nigeria', null, 'Documentary photographer', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-086', 'Zina Saro-Wiwo', 'Video', 'Lagos', 'Nigeria', null, 'Video artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-087', 'Chidinma Nnoli', 'Painting', 'Lagos', 'Nigeria', null, 'Surreal figurative painter', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-088', 'T. Adeyemi', 'Mixed media', 'Lagos', 'Nigeria', null, 'Lagos Nocturne artist', 'curated_public_repo_wayback', 'seed', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-089', 'Emerging Artist 089', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-090', 'Emerging Artist 090', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-091', 'Emerging Artist 091', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-092', 'Emerging Artist 092', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-093', 'Emerging Artist 093', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-094', 'Emerging Artist 094', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-095', 'Emerging Artist 095', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-096', 'Emerging Artist 096', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-097', 'Emerging Artist 097', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-098', 'Emerging Artist 098', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-099', 'Emerging Artist 099', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach'),
  ('ART-OUT-100', 'Emerging Artist 100', 'Mixed media', 'Lagos', 'Nigeria', null, 'Placeholder outreach slot — replace with verified artist', 'myafriart_outreach_pool', 'pending_verification', 'unclaimed_outreach', 'outreach')
on conflict (short_code) do update set
  name = excluded.name,
  primary_medium = excluded.primary_medium,
  domicile_city = excluded.domicile_city,
  country = excluded.country,
  website = excluded.website,
  outreach_note = excluded.outreach_note,
  outreach_source = excluded.outreach_source,
  outreach_status = excluded.outreach_status,
  profile_status = excluded.profile_status,
  content_source = excluded.content_source;
